name: Actions Test

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: issue number
        required: true
      label-name:
        description: label name
        required: true

jobs:
  add-comment:
    if: github.event.inputs.label-name == 'help-wanted'
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.inputs.issue-number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
