name: Auto Assign

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v1.1.2
