name: Create an issue

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Simple test issue
          body: |
            ### Tasks
            - [ ] 1st
            - [ ] 2nd
            - [ ] 3rd
