name: Escaped title

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Echo title
        run: echo ${{ github.event.pull_request.title }}

      - name: Escape title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        id: escape
        run: |
          ESCAPED_PR_TITLE="${PR_TITLE//\"/\\\"}"
          echo "title=$ESCAPED_PR_TITLE" >> $GITHUB_OUTPUT

      - name: Echo env title
        run: echo ${{ steps.set_title.title }}
