name: Escaped title

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Echo title
        run: echo ${{ github.event.pull_request.title }}

      - name: Echo concat title
        id: set_title
        run: echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT

      - name: Echo env title
        run: echo ${{ steps.set_title.title }}
