name: Escaped title

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Echo title
        run: echo ${{ github.event.pull_request.title }}
