name: Labeling

on:
  pull_request:

jobs:
  labeling:
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: frontend
        uses: yumemi-inc/path-filter@v2
        with:
          patterns: |
            **/*.js
            !server/**
          run: |
            gh pr edit ${{ github.event.number }} ${{ steps.filter.outputs.exists == 'true' && '--add-label' || '--remove-label' }} 'frontend'
      - name: ios
        uses: yumemi-inc/path-filter@v2
        with:
          patterns: |
            ios/**
          run: |
            gh pr edit ${{ github.event.number }} ${{ steps.filter.outputs.exists == 'true' && '--add-label' || '--remove-label' }} 'ios'
      - name: android
        uses: yumemi-inc/path-filter@v2
        with:
          patterns: |
            android/**
          run: |
            gh pr edit ${{ github.event.number }} ${{ steps.filter.outputs.exists == 'true' && '--add-label' || '--remove-label' }} 'android'
